### ISSUE TITLE
make met errors

### ISSUE THREAD

**Issue by archerhu77** [matszpk/amdcovc#1]
I had modify the ADL_SDK path in Makefile, when I use command "make", it show me following errors, how can I solve this problem?
I was use gcc version 6.3.0 (GCC)  to build the source.

[root@localhost amdcovc]# make
g++ -Wall -O3 -std=c++11 -I/root/setup/ADL_SDKV10.2//include -c -o amdcovc.o amdcovc.cpp
amdcovc.cpp: In destructor ‘ATIADLHandle::~ATIADLHandle()’:
amdcovc.cpp:230:34: warning: throw will always call terminate() [-Wterminate]
             throw Error(dlerror());
                                  ^
amdcovc.cpp:230:34: note: in C++11 destructors default to noexcept
amdcovc.cpp: At global scope:
amdcovc.cpp:611:26: error: ‘std::vector’ has not been declared
                     std::vector<int>& activeAdapters)
                          ^~~~~~
amdcovc.cpp:611:32: error: expected ‘,’ or ‘...’ before ‘<’ token
                     std::vector<int>& activeAdapters)
                                ^
amdcovc.cpp: In function ‘void getActiveAdaptersIndices(ADLMainControl&, int, int)’:
amdcovc.cpp:613:5: error: ‘activeAdapters’ was not declared in this scope
     activeAdapters.clear();
     ^~~~~~~~~~~~~~
amdcovc.cpp: At global scope:
amdcovc.cpp:620:24: error: ‘vector’ in namespace ‘std’ does not name a template type
             const std::vector<int>& activeAdapters,
                        ^~~~~~
amdcovc.cpp:620:30: error: expected ‘,’ or ‘...’ before ‘<’ token
             const std::vector<int>& activeAdapters,
                              ^
amdcovc.cpp: In function ‘void printAdaptersInfo(ADLMainControl&, int, int)’:
amdcovc.cpp:627:24: error: ‘choosenAdapters’ was not declared in this scope
     auto choosenIter = choosenAdapters.begin();
                        ^~~~~~~~~~~~~~~
amdcovc.cpp:632:13: error: ‘useChoosen’ was not declared in this scope
         if (useChoosen && (choosenIter==choosenAdapters.end() || *choosenIter!=i))
             ^~~~~~~~~~
amdcovc.cpp:665:13: error: ‘useChoosen’ was not declared in this scope
         if (useChoosen)
             ^~~~~~~~~~
amdcovc.cpp: At global scope:
amdcovc.cpp:672:24: error: ‘vector’ in namespace ‘std’ does not name a template type
             const std::vector<int>& activeAdapters,
                        ^~~~~~
amdcovc.cpp:672:30: error: expected ‘,’ or ‘...’ before ‘<’ token
             const std::vector<int>& activeAdapters,
                              ^
amdcovc.cpp: In function ‘void printAdaptersInfoVerbose(ADLMainControl&, int, int)’:
amdcovc.cpp:679:24: error: ‘choosenAdapters’ was not declared in this scope
     auto choosenIter = choosenAdapters.begin();
                        ^~~~~~~~~~~~~~~
amdcovc.cpp:684:13: error: ‘useChoosen’ was not declared in this scope
         if (useChoosen && (choosenIter==choosenAdapters.end() || *choosenIter!=i))
             ^~~~~~~~~~
amdcovc.cpp:743:13: error: ‘useChoosen’ was not declared in this scope
         if (useChoosen)
             ^~~~~~~~~~
amdcovc.cpp: At global scope:
amdcovc.cpp:749:56: error: ‘std::vector’ has not been declared
 static void parseAdaptersList(const char* string, std::vector<int>& adapters,
                                                        ^~~~~~
amdcovc.cpp:749:62: error: expected ‘,’ or ‘...’ before ‘<’ token
 static void parseAdaptersList(const char* string, std::vector<int>& adapters,
                                                              ^
amdcovc.cpp: In function ‘void parseAdaptersList(const char*, int)’:
amdcovc.cpp:752:5: error: ‘adapters’ was not declared in this scope
     adapters.clear();
     ^~~~~~~~
amdcovc.cpp:753:5: error: ‘allAdapters’ was not declared in this scope
     allAdapters = false;
     ^~~~~~~~~~~
amdcovc.cpp: At global scope:
amdcovc.cpp:809:10: error: ‘vector’ in namespace ‘std’ does not name a template type
     std::vector<int> adapters;
          ^~~~~~
amdcovc.cpp: In function ‘bool parseOVCParameter(const char*, OVCParameter&)’:
amdcovc.cpp:831:11: error: ‘struct OVCParameter’ has no member named ‘adapters’; did you mean ‘allAdapters’?
     param.adapters.clear();
           ^~~~~~~~
amdcovc.cpp:832:11: error: ‘struct OVCParameter’ has no member named ‘adapters’; did you mean ‘allAdapters’?
     param.adapters.push_back(0); // default is 0
           ^~~~~~~~
amdcovc.cpp:892:61: error: ‘struct OVCParameter’ has no member named ‘adapters’; did you mean ‘allAdapters’?
                 parseAdaptersList(listString.c_str(), param.adapters, param.allAdapters);
                                                             ^~~~~~~~
amdcovc.cpp: At global scope:
amdcovc.cpp:978:16: error: ‘vector’ in namespace ‘std’ does not name a template type
     const std::vector<int>& adapters;
                ^~~~~~
amdcovc.cpp:983:32: error: ‘vector’ in namespace ‘std’ does not name a template type
     AdapterIterator(const std::vector<int>& _adapters, bool _allAdapters,
                                ^~~~~~
amdcovc.cpp:983:38: error: expected ‘,’ or ‘...’ before ‘<’ token
     AdapterIterator(const std::vector<int>& _adapters, bool _allAdapters,
                                      ^
amdcovc.cpp: In constructor ‘AdapterIterator::AdapterIterator(int)’:
amdcovc.cpp:984:36: error: class ‘AdapterIterator’ does not have any field named ‘adapters’
             int _allAdaptersNum) : adapters(_adapters), allAdapters(_allAdapters),
                                    ^~~~~~~~
amdcovc.cpp:984:45: error: ‘_adapters’ was not declared in this scope
             int _allAdaptersNum) : adapters(_adapters), allAdapters(_allAdapters),
                                             ^~~~~~~~~
amdcovc.cpp:984:69: error: ‘_allAdapters’ was not declared in this scope
             int _allAdaptersNum) : adapters(_adapters), allAdapters(_allAdapters),
                                                                     ^~~~~~~~~~~~
amdcovc.cpp:985:28: error: ‘_allAdaptersNum’ was not declared in this scope
             allAdaptersNum(_allAdaptersNum), position(0)
                            ^~~~~~~~~~~~~~~
amdcovc.cpp: In member function ‘AdapterIterator::operator bool() const’:
amdcovc.cpp:996:48: error: ‘adapters’ was not declared in this scope
         return (!allAdapters && position < int(adapters.size())) ||
                                                ^~~~~~~~
amdcovc.cpp: In member function ‘bool AdapterIterator::operator!() const’:
amdcovc.cpp:1001:50: error: ‘adapters’ was not declared in this scope
         return !((!allAdapters && position < int(adapters.size())) ||
                                                  ^~~~~~~~
amdcovc.cpp: In member function ‘int AdapterIterator::operator*() const’:
amdcovc.cpp:1005:39: error: ‘adapters’ was not declared in this scope
     { return allAdapters ? position : adapters[position]; }
                                       ^~~~~~~~
amdcovc.cpp: At global scope:
amdcovc.cpp:1009:24: error: ‘vector’ in namespace ‘std’ does not name a template type
             const std::vector<int>& activeAdapters,
                        ^~~~~~
amdcovc.cpp:1009:30: error: expected ‘,’ or ‘...’ before ‘<’ token
             const std::vector<int>& activeAdapters,
                              ^
amdcovc.cpp: In function ‘void setOVCParameters(ADLMainControl&, int, int)’:
amdcovc.cpp:1019:33: error: ‘activeAdapters’ was not declared in this scope
     const int realAdaptersNum = activeAdapters.size();
                                 ^~~~~~~~~~~~~~
amdcovc.cpp:1020:5: error: ‘vector’ is not a member of ‘std’
     std::vector<ADLODParameters> odParams(realAdaptersNum);
     ^~~
amdcovc.cpp:1020:32: error: expected primary-expression before ‘>’ token
     std::vector<ADLODParameters> odParams(realAdaptersNum);
                                ^
amdcovc.cpp:1020:58: error: ‘odParams’ was not declared in this scope
     std::vector<ADLODParameters> odParams(realAdaptersNum);
                                                          ^
amdcovc.cpp:1021:5: error: ‘vector’ is not a member of ‘std’
     std::vector<std::vector<ADLODPerformanceLevel> > perfLevels(realAdaptersNum);
     ^~~
amdcovc.cpp:1021:17: error: ‘vector’ is not a member of ‘std’
     std::vector<std::vector<ADLODPerformanceLevel> > perfLevels(realAdaptersNum);
                 ^~~
amdcovc.cpp:1021:50: error: expected primary-expression before ‘>’ token
     std::vector<std::vector<ADLODPerformanceLevel> > perfLevels(realAdaptersNum);
                                                  ^
amdcovc.cpp:1021:52: error: expected primary-expression before ‘>’ token
     std::vector<std::vector<ADLODPerformanceLevel> > perfLevels(realAdaptersNum);
                                                    ^
amdcovc.cpp:1021:80: error: ‘perfLevels’ was not declared in this scope
     std::vector<std::vector<ADLODPerformanceLevel> > perfLevels(realAdaptersNum);
                                                                                ^
amdcovc.cpp:1022:5: error: ‘vector’ is not a member of ‘std’
     std::vector<std::vector<ADLODPerformanceLevel> > defaultPerfLevels(realAdaptersNum);
     ^~~
amdcovc.cpp:1022:17: error: ‘vector’ is not a member of ‘std’
     std::vector<std::vector<ADLODPerformanceLevel> > defaultPerfLevels(realAdaptersNum);
                 ^~~
amdcovc.cpp:1022:50: error: expected primary-expression before ‘>’ token
     std::vector<std::vector<ADLODPerformanceLevel> > defaultPerfLevels(realAdaptersNum);
                                                  ^
amdcovc.cpp:1022:52: error: expected primary-expression before ‘>’ token
     std::vector<std::vector<ADLODPerformanceLevel> > defaultPerfLevels(realAdaptersNum);
                                                    ^
amdcovc.cpp:1022:87: error: ‘defaultPerfLevels’ was not declared in this scope
     std::vector<std::vector<ADLODPerformanceLevel> > defaultPerfLevels(realAdaptersNum);
                                                                                       ^
amdcovc.cpp:1023:5: error: ‘vector’ is not a member of ‘std’
     std::vector<bool> changedDevices(realAdaptersNum);
     ^~~
amdcovc.cpp:1023:17: error: expected primary-expression before ‘bool’
     std::vector<bool> changedDevices(realAdaptersNum);
                 ^~~~
amdcovc.cpp:1024:15: error: ‘changedDevices’ was not declared in this scope
     std::fill(changedDevices.begin(), changedDevices.end(), false);
               ^~~~~~~~~~~~~~
amdcovc.cpp:1027:30: error: ‘ovcParams’ was not declared in this scope
     for (OVCParameter param: ovcParams)
                              ^~~~~~~~~
amdcovc.cpp:1031:42: error: ‘struct OVCParameter’ has no member named ‘adapters’; did you mean ‘allAdapters’?
             for (int adapterIndex: param.adapters)
                                          ^~~~~~~~
amdcovc.cpp:1041:30: error: ‘ovcParams’ was not declared in this scope
     for (OVCParameter param: ovcParams)
                              ^~~~~~~~~
amdcovc.cpp:1071:30: error: ‘ovcParams’ was not declared in this scope
     for (OVCParameter param: ovcParams)
                              ^~~~~~~~~
amdcovc.cpp:1073:44: error: ‘struct OVCParameter’ has no member named ‘adapters’; did you mean ‘allAdapters’?
             for (AdapterIterator ait(param.adapters, param.allAdapters, realAdaptersNum);
                                            ^~~~~~~~
amdcovc.cpp:1130:30: error: ‘ovcParams’ was not declared in this scope
     for (OVCParameter param: ovcParams)
                              ^~~~~~~~~
amdcovc.cpp:1132:44: error: ‘struct OVCParameter’ has no member named ‘adapters’; did you mean ‘allAdapters’?
             for (AdapterIterator ait(param.adapters, param.allAdapters, realAdaptersNum);
                                            ^~~~~~~~
amdcovc.cpp:1143:30: error: ‘ovcParams’ was not declared in this scope
     for (OVCParameter param: ovcParams)
                              ^~~~~~~~~
amdcovc.cpp:1145:44: error: ‘struct OVCParameter’ has no member named ‘adapters’; did you mean ‘allAdapters’?
             for (AdapterIterator ait(param.adapters, param.allAdapters, realAdaptersNum);
                                            ^~~~~~~~
amdcovc.cpp:1185:5: error: ‘vector’ is not a member of ‘std’
     std::vector<FanSpeedSetup> fanSpeedSetups(realAdaptersNum);
     ^~~
amdcovc.cpp:1185:30: error: expected primary-expression before ‘>’ token
     std::vector<FanSpeedSetup> fanSpeedSetups(realAdaptersNum);
                              ^
amdcovc.cpp:1185:62: error: ‘fanSpeedSetups’ was not declared in this scope
     std::vector<FanSpeedSetup> fanSpeedSetups(realAdaptersNum);
                                                              ^
amdcovc.cpp:1188:30: error: ‘ovcParams’ was not declared in this scope
     for (OVCParameter param: ovcParams)
                              ^~~~~~~~~
amdcovc.cpp:1190:44: error: ‘struct OVCParameter’ has no member named ‘adapters’; did you mean ‘allAdapters’?
             for (AdapterIterator ait(param.adapters, param.allAdapters, realAdaptersNum);
                                            ^~~~~~~~
amdcovc.cpp:1198:30: error: ‘ovcParams’ was not declared in this scope
     for (OVCParameter param: ovcParams)
                              ^~~~~~~~~
amdcovc.cpp:1200:44: error: ‘struct OVCParameter’ has no member named ‘adapters’; did you mean ‘allAdapters’?
             for (AdapterIterator ait(param.adapters, param.allAdapters, realAdaptersNum);
                                            ^~~~~~~~
amdcovc.cpp: In function ‘int main(int, const char**)’:
amdcovc.cpp:1317:5: error: ‘vector’ is not a member of ‘std’
     std::vector<OVCParameter> ovcParameters;
     ^~~
amdcovc.cpp:1317:29: error: expected primary-expression before ‘>’ token
     std::vector<OVCParameter> ovcParameters;
                             ^
amdcovc.cpp:1317:31: error: ‘ovcParameters’ was not declared in this scope
     std::vector<OVCParameter> ovcParameters;
                               ^~~~~~~~~~~~~
amdcovc.cpp:1318:5: error: ‘vector’ is not a member of ‘std’
     std::vector<int> choosenAdapters;
     ^~~
amdcovc.cpp:1318:17: error: expected primary-expression before ‘int’
     std::vector<int> choosenAdapters;
                 ^~~
amdcovc.cpp:1330:43: error: ‘choosenAdapters’ was not declared in this scope
             parseAdaptersList(argv[i]+11, choosenAdapters, chooseAllAdapters);
                                           ^~~~~~~~~~~~~~~
amdcovc.cpp:1337:46: error: ‘choosenAdapters’ was not declared in this scope
                 parseAdaptersList(argv[++i], choosenAdapters, chooseAllAdapters);
                                              ^~~~~~~~~~~~~~~
amdcovc.cpp:1346:46: error: ‘choosenAdapters’ was not declared in this scope
                 parseAdaptersList(argv[i]+2, choosenAdapters, chooseAllAdapters);
                                              ^~~~~~~~~~~~~~~
amdcovc.cpp:1348:46: error: ‘choosenAdapters’ was not declared in this scope
                 parseAdaptersList(argv[++i], choosenAdapters, chooseAllAdapters);
                                              ^~~~~~~~~~~~~~~
amdcovc.cpp:1383:5: error: ‘vector’ is not a member of ‘std’
     std::vector<int> activeAdapters;
     ^~~
amdcovc.cpp:1383:17: error: expected primary-expression before ‘int’
     std::vector<int> activeAdapters;
                 ^~~
amdcovc.cpp:1384:56: error: ‘activeAdapters’ was not declared in this scope
     getActiveAdaptersIndices(mainControl, adaptersNum, activeAdapters);
                                                        ^~~~~~~~~~~~~~
amdcovc.cpp:1388:32: error: ‘choosenAdapters’ was not declared in this scope
         for (int adapterIndex: choosenAdapters)
                                ^~~~~~~~~~~~~~~
amdcovc.cpp:1398:25: error: ‘choosenAdapters’ was not declared in this scope
                         choosenAdapters, useAdaptersList && !chooseAllAdapters);
                         ^~~~~~~~~~~~~~~
amdcovc.cpp:1401:25: error: ‘choosenAdapters’ was not declared in this scope
                         choosenAdapters, useAdaptersList && !chooseAllAdapters);
                         ^~~~~~~~~~~~~~~
make: *** [amdcovc.o] Error 1

**Comment by matszpk** [comment]
Ok. I added a missing include <vector> to sources. Try again.

**Comment by archerhu77** [comment]
It woks! Thank you!
