### ISSUE TITLE
make issue /usr/bin/ld: cannot find -lpci  (Ubuntu 16.04.3 LTS)

### ISSUE THREAD

**Issue by StorageGuru** [matszpk/amdcovc#10]
Hi there,
I should have installed all the requirements:
- OpenCL environemnt (guess it's installed with the AMD drivers amdgpu-pro-17.30-465504.tar.xz)
- pciutils in  /home/miner/pciutils  (compilation went through)
- libadlxx.so library (AMD ADL library)    thought they'd come with 
   ADL SDK V 10   http://developer.amd.com/display-library-adl-sdk/  but this file is not included in zip file!!!

Makefile 
  ADLSDKDIR = /home/miner/treiber/AMD_ADL
  PCIDIR = /home/miner/pciutils
  CXX = g++
  CXXFLAGS = -Wall -O3 -std=c++11
  LDFLAGS = -Wall -O3 -std=c++11
  INCDIRS = -I$(ADLSDKDIR)/include -I$(PCIDIR)
  LIBDIRS = -L/opt/amdgpu-pro/lib/x86_64-linux-gnu
  #LIBDIRS =
   LIBS = -ldl -lpci -lm -lOpenCL -pthread
[...]

If I run make I run into this:
miner@erpel2:~/amdcovc$ make
g++ -Wall -O3 -std=c++11 -L/opt/amdgpu-pro/lib/x86_64-linux-gnu  -o amdcovc amdcovc.o -ldl -lpci -lm -lOpenCL -pthread
/usr/bin/ld: cannot find -lpci
collect2: error: ld returned 1 exit status
Makefile:25: recipe for target 'amdcovc' failed
make: *** [amdcovc] Error 1

Unfortunately I am far from being a Linux champion so any hint is appreciated .
Thanks, Stefan

**Comment by matszpk** [comment]
To build amdcovc, you should install libpci-dev, libpci3 and pciutils packages (by apt-get install). Any user built of pciutils is not needed. This library and its development files are needed in system (this is recommended place) to build amdcovc.

**Comment by StorageGuru** [comment]
Hi matszpk, *many thanks*, that fixed it and I got amdcvoc running. However the output "VDDC voltage available only for AMD Catalyst/Crimson drivers." indicates that I cannot undervolt in Linux as Crimson drivers only support Windows, right ?
