### ISSUE TITLE
No change in core clocks or mem clocks

### ISSUE THREAD

**Issue by syntaxcollector** [matszpk/amdcovc#12]
Hi there :) 

I'm using Ubuntu LTS 16.04.3. I installed the SDK10 AMD ADL libraries for your utility as well as the rest of the requirements. It compiled without issue although it would've been easier if the docs said somewhere to copy the include folder from the ADL SDK to one level up of the amdcovc build folder. Took me a few minutes to figure out where to put it. 

Anyways, after it finishes I can print the output for my GPU. 

> tjadmin@rig03:~/overclock/amdcovc-master$ sudo ./amdcovc -a 1
> Adapter 1: Hawaii PRO [Radeon R9 290]
>   Core: 1040 MHz, Mem: 1250 MHz, CoreOD: 0, MemOD: 0, Load: 100%, Temp: 62 C, Fan: 43.9216%
>   Core clocks: 300 483 727 924 968 1004 1031 1040
>   Memory Clocks: 150 1250

I then issue this command

> sudo ./amdcovc coreclk:1:0=1140

The command responds

> tjadmin@rig03:~/overclock/amdcovc-master$ sudo ./amdcovc coreclk:1:0=1140
> WARNING: setting AMD Overdrive parameters!
> 
> IMPORTANT NOTICE: Before any setting of AMD Overdrive parameters,
> please STOP ANY GPU computations and GPU renderings.
> Please use this utility CAREFULLY, because it can DAMAGE your hardware!
> 
> Setting core clock to 1140 MHz for adapter 1 at performance level 0

However the output of the card still says 1040 after

> tjadmin@rig03:~/overclock/amdcovc-master$ sudo ./amdcovc -a 1
> Adapter 1: Hawaii PRO [Radeon R9 290]
>   Core: 1040 MHz, Mem: 1250 MHz, CoreOD: 0, MemOD: 0, Load: 100%, Temp: 61 C, Fan: 42.7451%
>   Core clocks: 300 483 727 924 968 1004 1031 1040
>   Memory Clocks: 150 1250

What am I doing wrong here? 

Best
Jordan

**Comment by matszpk** [comment]
Unfortunatelly, AMDGPU(-PRO) drivers support overclocking features only for Radeon Fury/Radeon RX 400/500/VEGA series. Overclocking under AMDGPU(-PRO) drivers doesn't work for GPU's based on GCN 1.0/1.1 architecture (R9 290/390 and older HD7000 series). I was checking, overcloking doesn't work on my Radeon R7 360 on that drivers :(
