### ISSUE TITLE
Help please: relocation error: ./amdcovc: symbol pci_init, version LIBPCI_3.2 not defined in file libpci.so.3 with link time reference

### ISSUE THREAD

**Issue by tommy1735** [matszpk/amdcovc#16]
hi

please help me i cannot run this tool its gives me that error:

```
root@i7:~/amdcovc-0.3.0pre5# ./amdcovc -v
./amdcovc: relocation error: ./amdcovc: symbol pci_init, version LIBPCI_3.2 not defined in file libpci.so.3 with link time reference
```

OS info:
```
root@i7:~/amdcovc-0.3.0pre5# uname -a
Linux i7 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@i7:~/amdcovc-0.3.0pre5# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

running with 2 RX580 mining ethereum....
would like to lower the voltage to keep it cooler... any idea is very welcome

**Comment by matszpk** [comment]
I recommend to build own version from sources. This is typical error. Binaries requires particular libpci version. I wrote about that in release's description. I encountered similar problem on my other system with gentoo linux.
