### ISSUE TITLE
Overclock HELP PLEASE

### ISSUE THREAD

**Issue by minitzi** [matszpk/amdcovc#18]
Ubuntu 16.04.3 LTS 
root@rig-desktop:~/amdcovc-master# uname -r
4.10.0-28-generic

AMDGPU-PRO 17.40
Rx 580  8 Gb 

root@rig-desktop:~/amdcovc-master# ./amdcovc coreclk:0=1000 memclk:0=1200
WARNING: setting AMD Overdrive parameters!

IMPORTANT NOTICE: Before any setting of AMD Overdrive parameters,
please STOP ANY GPU computations and GPU renderings.
Please use this utility CAREFULLY, because it can DAMAGE your hardware!

Core clock out of range in 'coreclk:0=1000'!
Memory clock out of range in 'memclk:0=1200'!
NO ANY settings applied. Error in parameters!
Wrong parameters!

Can anybody explain how to overclock them and undervolt ? 
Im using Claymore to mine ethereum.
Thanks.

**Comment by matszpk** [comment]
In your case, you tried to underclock your graphics by using amdcovc and AMDGPU-PRO 17.40. In this case, this is not possible, because amdcovc with AMDGPU-PRO drivers only allows to overclock core or memory (from 0 to 20%).

**Comment by minitzi** [comment]
do you have any ideea how can i underclock my gpus ? 
using ubuntu 16.04 and amdgpupro 17.40 ? 

what driver do i need to get 30MH + from each card ?
I tryed simplemining and the gpus are making there 30+

Thanks in advance.

**Comment by matszpk** [comment]
Currently, simple way to underclock graphics card under the AMDGPU-PRO drivers control does not exist. The amdcovc uses standard and known features of AMDGPU(-PRO) drivers to change core and memory clock and fanspeed.
