### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by archerhu77** [matszpk/amdcovc#2]
CentOS7
ADL SDK V12.0

Compile success.
Run ./amdcovc -?   ........ ok
Run ./amdcovc -v   ........ show following error:
libatiadlxx.so: cannot open shared object file: No such file or directory

**Comment by matszpk** [comment]
AMD Catalyst/Crimson drivers (with libatialdxx library) is required to run program. Program search that library standard locations (/usr/lib64). If you are using AMDGPU-PRO or AMDGPU drivers this utility is obsolete (setting overclocking params can be done by writing specific files to /sys directory).

**Comment by archerhu77** [comment]
I use the driver "amdgpu-pro-16.60-379184", and I couldn't find any file what name like this.

[root@localhost amdgpu-pro]# find / -name \*atiadl\*.so

I am sure that I was install amdgpu-pro driver correctly.

**Comment by matszpk** [comment]
IMHO, AMDGPU-PRO doesn't provide that library. Currently, this utility does not support AMDGPU-PRO drivers :(. maybe later this feature will be added.

**Comment by archerhu77** [comment]
"this utility does not support AMDGPU-PRO drivers" Oh, no~~~~

**Comment by medonyo** [comment]
It looks like AMD strangely forget to include this libatiadlxx.so library even in its offitial downloads:
http://developer.amd.com/tools-and-sdks/graphics-development/display-library-adl-sdk/
there are only headers included and no library at all for linux.
Neverthe less I've found that it is available for SteamOS - that seems even more streange to me, but that is true.
http://repo.steampowered.com/steamos/pool/non-free/a/amdgpu-pro-installer/

I thought that it would be fine having this library but after running I'am still getting:
ddd@fff:~/temp/amdcovc-0.2.1$ ./amdcovc 
/usr/lib/libatiadlxx.so: undefined symbol: ADL_ConsoleMode_FileDescriptor_Set        

Now I will try to write to the /sys devices as matszpk suggested. It should make life easier if it can be done this way :).

**Comment by matszpk** [comment]
Now, amdcovc supports AMDGPU(-PRO) drivers.
