### ISSUE TITLE
ADLSDK fails

### ISSUE THREAD

**Issue by nachitox** [matszpk/amdcovc#22]
I'm trying to read voltages but can't make it work.

I compiled it with `HAVE_ADLSDK = 1` pointing `ADLSDKDIR` to the right dir and setting `LIBDIRS` to the Ubuntu line.
I have installed Radeon™ Software for Linux® Driver 17.50

I don't know why but `if (handle.open())` fails.

**Comment by matszpk** [comment]
The ADLSDK requires old AMD Catalyst drivers published before 2016 (AMD Catalyst 15.XX or earlier). AMDGPU-PRO  (your AMD linux driver is very likely AMDGPU-PRO driver) and AMDGPU does not deliver needed ADL, thus AMDCOVC uses other way to read and write parameters.
AMDGPU-PRO does not give (officially) and any way to set GPU voltage.

**Comment by nachitox** [comment]
I understand. Thank you.
