### ISSUE TITLE
Cant see (or set) the Vddc values on Rx570 

### ISSUE THREAD

**Issue by Integrative** [matszpk/amdcovc#23]
Compiled on Ubuntu 16.04, kernel 4.8.0-58 with ADL 10.02 and openCL from AMD 17.5 Driver

kernel 4.17+ should expose Power values through DRM?
```

Adapter 0: Device 67df
  Core: 1244 MHz, Mem: 1750 MHz, CoreOD: 0, MemOD: 0, Load: 100%, Temp: 57 C, Fan: 72.9412%
  Core clocks: 300 588 952 1041 1106 1168 1209 1244
  Memory Clocks: 300 1000 1750
Adapter 1: Device 67df
```
etc....

**Comment by matszpk** [comment]
Unfortunatelly, new AMDGPU-PRO drivers doesn't provide ADL interface to read device parameters (including voltages). AMDGPU-PRO uses other interface from AMDGPU which doesn't provide informations about voltage. The new features included (wattman like features) in kernel 4.17 will be added to amdcovc later.

**Comment by ck-kc** [comment]
Any timeline on adding the wattman like features now that linux 4.17 is released? Or any alternative tools that exist?

**Comment by matszpk** [comment]
Requested feature will be added in the closest time when I will find some free time to do it. Now, I built in my system kernel 4.17 and I will be testing that kernel.

**Comment by matszpk** [comment]
Support for voltage from AMDGPU drivers has been added.
