### ISSUE TITLE
Configure all adapters

### ISSUE THREAD

**Issue by FieryBeard** [matszpk/amdcovc#27]
Can I configure all the adapters without enumeration with one command?

**Comment by matszpk** [comment]
Ofcourse, yes. you can use 'all' as list of the adapters like `amdcovc fanspeed:all=default` - this command set default fanspeed for all adapters, or `amdcovc coreclk:all=1000` - set 1000 MHz core clock for all adapters.

**Comment by matszpk** [comment]
More info about list of adapters has been added to README.md.

**Comment by matszpk** [comment]
Yet another way to choose many adapters - use ranges: `amdcovc coreclk:0-3=1000` - set core clock to 1000 for adapters 0,1,2,3. You can mix numbers, ranges in single list like: `0,2-4,7`.

**Comment by FieryBeard** [comment]
Thanks!
