### ISSUE TITLE
Feature Request: Colorized output

### ISSUE THREAD

**Issue by NetworkJack2** [matszpk/amdcovc#31]
I am requesting that output be colorized to improve readibility:

Bold: All titles on monitoring be bolded.

All Warnings be yellow, all critical reports(like fan or temp) be red.

The current clock speeds and available clock speeds should be various colors so they pop out at the user.

**Comment by matszpk** [comment]
Now initially added to 0.3.10pre1 version.

**Comment by NetworkJack2** [comment]
w00t. Awesome. thanks
