### ISSUE TITLE
not work::  Can I treat R7 360 with amdcovc? 

### ISSUE THREAD

**Issue by hitobashira** [matszpk/amdcovc#5]
./amdcovc -v
basic_ios::clear: iostream error

--------------
System: Kernel: 4.4.0-78-generic x86_64 (64 bit) Desktop: Cinnamon 3.4.1
           Distro: Linux Mint 18.2 Sonya
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. **[AMD/ATI] Tobago PRO [Radeon R7 360** / R9 360 OEM] (rev 81) (prog-if 00 [VGA controller])
	Subsystem: PC Partner Limited / Sapphire Technology Tobago PRO [**Radeon R7 360** / R9 360 OEM]
	Flags: bus master, fast devsel, latency 0, IRQ 47
	Memory at c0000000 (64-bit, prefetchable) [size=256M]
	Memory at d0000000 (64-bit, prefetchable) [size=8M]
	I/O ports at e000 [size=256]
	Memory at fea00000 (32-bit, non-prefetchable) [size=256K]
	Expansion ROM at fea40000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: radeon
	Kernel modules: radeon

**Comment by matszpk** [comment]
I ran amdcovc on Ubuntu 16.04 with builtin Radeon drivers. It display info correctly. Can you run amdcovc under strace or other debug utility to find last open() call? In, the next pre-release if will fixed error handling to make finding that errors easier.

**Comment by hitobashira** [comment]
Thank you.
I was careless. 
Currently, I used a development version driver .
instead of an official Stable version.
http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu xenial InRelease
