### ISSUE TITLE
Question about overclocking

### ISSUE THREAD

**Issue by kwiksand** [matszpk/amdcovc#7]
I've noticed I can't actually set my clock speed past their defaults (i.e the bounds of the clock rates available):

`ccgamer@trusk:~/amdcovc$ ./amdcovc
Adapter 0: Device 67df
  Core: 300 MHz, Mem: 300 MHz, CoreOD: 0, MemOD: 0, Temp: 58 C, Fan: 16.8627%
  Core clocks: 300 588 952 1041 1106 1168 1209 1340
  Memory Clocks: 300 1000 1750
Adapter 1: Device 67df
  Core: 300 MHz, Mem: 300 MHz, CoreOD: 0, MemOD: 0, Temp: 58 C, Fan: 24.7059%
  Core clocks: 300 588 952 1041 1106 1168 1209 1340
  Memory Clocks: 300 1000 1750`

On Windows, I can quite happily set the memory clock up to 2240 (stable), but I don't seem to be able to use something that's not 300, 1000, 1750 in the above case.  Do I need to add more usable memory clock's to a config file somewhere?

**Comment by matszpk** [comment]
Memory clock 2240 MHz is beyond value acceptable by amdcovc and (possible) by driver. In my knowledge, drivers (amdgpu-pro and opensource amdgpu) accept only values higher by 20% than nominal clocks. ofcourse you can put your value to file "/sys/class/drm/card?/device/pp_mclk_od", however likely will not impact on clocks.

**Comment by int03h** [comment]
This tool is WIP. It is good, but it isn't complete. Many of the things that are considered standard in windows are considered hacks in Linux. This tool  is in the "won't break your shit" category.  As the poster above mentions, there are enumerated device nodes that can be probed and poked, some work, some don't. Some persist .. others don't. Some depend on the kernel nodes, others on the amdgpu-pro enumeration.  The CURRENT OFFICIAL way to do what you are trying to do is with this https://github.com/RadeonOpenCompute/ROC-smi - touching the memclk and/or the VDDC are not possible, and source code is not provided either. There are folks that are doing some of this via the VBIOS.  https://github.com/OhGodACompany/OhGodATool .. the documentation is scant. But these folks are legit and know what they are doing, so I have no doubt that their claims are possible.

**Comment by kwiksand** [comment]
Thanks, clears things up!
