### ISSUE TITLE
Performance level out of range in 'memclk:0:1=900'!

### ISSUE THREAD

**Issue by itinance** [matszpk/amdcovc#8]
I get always the following error:

```
user@mine1:~$ sudo amdcovc memclk:0:1=900
WARNING: setting AMD Overdrive parameters!

IMPORTANT NOTICE: Before any setting of AMD Overdrive parameters,
please STOP ANY GPU computations and GPU renderings.
Please use this utility CAREFULLY, because it can DAMAGE your hardware!

Performance level out of range in 'memclk:0:1=900'!
NO ANY settings applied. Error in parameters!
```

The same happens with all commands found in the list of examples, e.g.

`amdcovc coreclk:1:0=900 coreclk:0:1=1000`

Do I miss something or pass wrong values?

Setup:

Ubuntu 16.04, Radeon RX 580, OpenCL installed.
```

user@mine1:~$ uname -a
Linux mine1 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
user@mine1:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

amdcovc:
```
user@mine1:~$ amdcovc
Adapter 0: Device 67df
  Core: 1365 MHz, Mem: 1750 MHz, CoreOD: 0, MemOD: 0, Temp: 72 C, Fan: 72.9412%
  Core clocks: 300 600 900 1145 1215 1257 1300 1365
  Memory Clocks: 300 1000 1750
Adapter 1: Device 67df
  Core: 1365 MHz, Mem: 1750 MHz, CoreOD: 0, MemOD: 0, Temp: 72 C, Fan: 46.6667%
  Core clocks: 300 600 900 1145 1215 1257 1300 1365
  Memory Clocks: 300 1000 1750
Adapter 2: Device 67df
  Core: 1365 MHz, Mem: 1750 MHz, CoreOD: 0, MemOD: 0, Temp: 72 C, Fan: 81.9608%
  Core clocks: 300 600 900 1145 1215 1257 1300 1365
  Memory Clocks: 300 1000 1750
... and so on
```

**Comment by matszpk** [comment]
This is known error committed by users. In your case correct memory range is 1750-2100. amdcovc with AMDGPU(-PRO) accepts only values between max memory clock and 20% higher. In your case value is too low.
EDIT: Unfortunatelly, memory overclocking doesn't work correctly with current AMDGPU-PRO drivers (I don't know how it is working with open-source AMDGPU drivers). After changing memory clock, drivers set up lowest memory clock. Ofcourse you can check whether memory overclocking works correctly.

**Comment by itinance** [comment]
Thanks for this incredible fast clarifying! :)

What i want to do is to down-clock the GPU instead of overclocking. Apparently it is not possible this way. Thanks.
