### ISSUE TITLE
libatiadlxx.so not found

### ISSUE THREAD

**Issue by BrockChen** [matszpk/amdcovc#9]
I installed amdgpu-pro-17.30, but there are not include this library?
how to resolve the problem?

**Comment by fractalyse** [comment]
Hi,
You have to install [AMD APP SDK](http://developer.amd.com/amd-accelerated-parallel-processing-app-sdk/)

Cheers.

**Comment by BrockChen** [comment]
Yes, I did. 
./AMD-APP-SDK-v3.0.130.136-GA-linux64.sh

But the problem still there

**Comment by fractalyse** [comment]
Oups, sorry you need to install [AMD ADL LIBRARY](http://developer.amd.com/display-library-adl-sdk/
)
Once you've installed it, you have to replace "ADLSDKDIR" in makefile with the proper path.

**Comment by matszpk** [comment]
Yes. amdcovc needs ADL SDK to build. It handle both AMD Catalyst and AMDGPU(-PRO) drivers. Later, I will add option to choose what driver should be supported by amdcovc.

**Comment by matszpk** [comment]
Problem has been resolved. Now it is possible to disable ADLSDK support in Makefile.
